// Top-level build file for Netscape Sovereign Hub
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // This provides the 'com.android.application' plugin
        classpath 'com.android.tools.build:gradle:7.1.3'
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // Essential for Mesibo v2
        maven { url 'https://mesibo.com/maven' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
