buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Upgraded for Java 11/17 compatibility
        classpath "com.android.tools.build:gradle:7.0.4"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
